### ISSUE TITLE
'explode' should be populated with specified default values

### ISSUE THREAD

**Issue by ugexe** [croservices/openapi-model#3]
https://github.com/croservices/openapi-model/blob/036dc0b9c706dd0e1e44efdfa84a854face440ff/lib/OpenAPI/Model/OpenAPI.pm6#L298
https://github.com/croservices/openapi-model/blob/036dc0b9c706dd0e1e44efdfa84a854face440ff/lib/OpenAPI/Model/OpenAPI.pm6#L311

---

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#operationObject
> When this is true, parameter values of type array or object generate separate parameters for each value of the array or key-value pair of the map. For other types of parameters this property has no effect. When style is form, the default value is true. For all other styles, the default value is false.

**Comment by Altai-man** [comment]
Closed with https://github.com/croservices/openapi-model/commit/de12d08c79fbe0a197afe89e0a35da4af7cbe788
