### ISSUE TITLE
'style' should be populated with specified default values 

### ISSUE THREAD

**Issue by ugexe** [croservices/openapi-model#4]
https://github.com/croservices/openapi-model/blob/036dc0b9c706dd0e1e44efdfa84a854face440ff/lib/OpenAPI/Model/OpenAPI.pm6#L295-L296
https://github.com/croservices/openapi-model/blob/036dc0b9c706dd0e1e44efdfa84a854face440ff/lib/OpenAPI/Model/OpenAPI.pm6#L309

---

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#operationObject
> Describes how the parameter value will be serialized depending on  the type of the parameter value. Default values (based on value of in): for query - form; for path - simple; for header - simple; for cookie - form.

**Comment by Altai-man** [comment]
I fixed both this and https://github.com/croservices/openapi-model/issues/3 issues locally, along with some tests. It will be pushed as soon as the access to the repo will be granted to me. :)

**Comment by Altai-man** [comment]
Should be fixed with https://github.com/croservices/openapi-model/commit/de12d08c79fbe0a197afe89e0a35da4af7cbe788 - also, quite a serious bug was found while fixing it, made an issue at https://github.com/croservices/openapi-model/issues/6.
Re-open if needed.
